# Generated by Django 4.2 on 2023-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="question",
            field=models.TextField(default="No question"),
        ),
        migrations.AlterField(
            model_name="response",
            name="score",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="response",
            name="text",
            field=models.TextField(default="No response"),
        ),
    ]
